projects:
  nationalparks:
    schemaPath: src/graphql/schema.json
    includes:
      - nationalpark
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
